ApplicationAsset:
  columns:
    application_id:
      type: integer
      primary: true
    asset_id:
      type: integer
      primary: true
      
  relations:
    Application:
      class: Application
    Asset:
      class: Asset
      
  options:
    type: INNODB
    collate: utf8_bin
    charset: utf8
