Application:
  tableName: system_application
  columns:
    name: 
      type: string(255)
      unique: true
    title:
      type: string(255)
    description:
      type: clob
    version:
      type: string(255)
    url:
      type: string(255)
    status:
      type: enum
      length: 7
      values: ['active', 'passive']
      default: 'active'
      
  actAs:
    I18n:
      fields: [title, description]
      className: ApplicationTranslation
      length: 5
    SoftDelete:
     
  relations:
    Assets:
      foreignAlias: Asset
      class: Asset
      refClass: ApplicationAsset
      
  options:
    type: INNODB
    collate: utf8_bin
    charset: utf8
