production:
  general:
    project:
      folder: "kebab-reloaded"
      version: "1.5.0 Pre-Alpha"
      url: "http://localhost/kebab-reloaded/"
  logger:
    use: false
    folder: logs
    file: application.log
    stream:
      use: false
    fireBug:
      use: true
  vendors:
    zf:
      version: 1.11.0
    extJs:
      version: 3.3.3
      cdn:
        use: 1
        url: "http://extjs.cachefly.net/"
      debug: false

staging:
  _extends: production
  vendors:
    extJs:
      cdn:
        use: true

testing:
  _extends: production
  vendors:
    extJs:
      debug: true
  logger:
    use: true
    stream:
      use: true

development:
  _extends: production
  vendors:
    extJs:
      debug: true
  logger:
    use: true
    stream:
      use: true